import express from 'express';
import { store } from './store.js';
import { createSession, createTrade, recomputeSessionStats } from './models.js';
import { checkHaltConditions, evaluateLiveGate, canTradeMarket } from './safetyEngine.js';
import { getAccount, getPositions, getTradableAssets, getMarketClock, getStockSnapshots, getCryptoSnapshots, getLatestTradablePrice, hasCredentials, placeOrder, waitForFill } from './alpacaClient.js';

const router = express.Router();
const state = { running:false, timer:null, sessionId:null, startedAt:null, lastTickAt:null, lastError:null, openTradeId:null, lastDecision:'stopped', signalSnapshot:{}, topCandidates:[], universe:{equities:[],crypto:[],refreshedAt:null}, equityCursor:0, marketOpen:null };
const DEFAULTS = { pollSeconds:5, entryMomentumPct:0.15, takeProfitPct:0.6, stopLossPct:0.4, maxHoldMinutes:15, equityBatchSize:75, universeRefreshMinutes:15, minEquityPrice:1, minDailyDollarVolume:1000000, stockFeed:'iex' };
const tradingCfg=()=>({ startingCapital:100, riskPerTrade:0.02, ...store.getConfig('tradingConfig',{}) });
const cfg=()=>({ ...DEFAULTS, ...store.getConfig('liveBotConfig',{}) });
function gate(){ return evaluateLiveGate({ consents:store.getConfig('liveGateConsents',{}), hasLiveCredentials:hasCredentials('live') }); }
function pub(){ return { running:state.running, sessionId:state.sessionId, startedAt:state.startedAt, lastTickAt:state.lastTickAt, lastError:state.lastError, openTradeId:state.openTradeId, lastDecision:state.lastDecision, signalSnapshot:state.signalSnapshot, topCandidates:state.topCandidates, marketOpen:state.marketOpen, universe:{ equityCount:state.universe.equities.length, cryptoCount:state.universe.crypto.length, totalCount:state.universe.equities.length+state.universe.crypto.length, refreshedAt:state.universe.refreshedAt, equityCursor:state.equityCursor }, config:{...cfg(), riskPerTrade:Number(tradingCfg().riskPerTrade ?? 0.02), sizingMode:'equity_risk_fraction'} }; }
function stop(reason=null){ if(state.timer) clearTimeout(state.timer); state.timer=null; state.running=false; if(reason) state.lastError=reason; }
function schedule(){ if(state.running) state.timer=setTimeout(tick,Math.max(2,Number(cfg().pollSeconds))*1000); }
function normPos(s=''){ if(s.includes('/')) return s; if(/^[A-Z]+USD$/.test(s)) return `${s.slice(0,-3)}/USD`; return s; }
async function refreshUniverse(force=false){ const c=cfg(); const age=state.universe.refreshedAt?Date.now()-new Date(state.universe.refreshedAt).getTime():Infinity; if(!force&&age<Number(c.universeRefreshMinutes)*60000)return; const a=await getTradableAssets('live'); state.universe={equities:a.equities,crypto:a.crypto,refreshedAt:new Date().toISOString()}; if(state.equityCursor>=a.equities.length)state.equityCursor=0; }
function mom(x){ const b=x?.minuteBar, o=Number(b?.o), c=Number(b?.c ?? x?.latestTrade?.p); if(!Number.isFinite(o)||!Number.isFinite(c)||o<=0)return null; return {momentumPct:((c-o)/o)*100,price:c,volume:Number(x?.dailyBar?.v||0)}; }
async function scan(){
  await refreshUniverse(); const c=cfg(); const session=store.getOne('sessions',state.sessionId); const trades=store.getAll('trades').filter(t=>t.session_id===session.id); const positions=await getPositions('live'); const blocked=new Set(positions.filter(p=>Math.abs(Number(p.qty||0))>0).map(p=>normPos(p.symbol))); const candidates=[]; const snapOut={};
  const cs=state.universe.crypto.map(a=>a.symbol).filter(Boolean); if(cs.length){ const snaps=await getCryptoSnapshots('live',cs); for(const a of state.universe.crypto){ const x=snaps[a.symbol]||snaps[a.symbol?.replace('/','')], m=mom(x); if(!m)continue; const eligible=!blocked.has(a.symbol)&&canTradeMarket(trades,a.symbol); snapOut[a.symbol]={assetClass:'crypto',momentumPct:Number(m.momentumPct.toFixed(4)),thresholdPct:c.entryMomentumPct,eligible}; if(eligible&&m.momentumPct>=c.entryMomentumPct)candidates.push({symbol:a.symbol,name:a.name||a.symbol,assetClass:'crypto',...m}); }}
  const clock=await getMarketClock('live'); state.marketOpen=Boolean(clock?.is_open); if(state.marketOpen&&state.universe.equities.length){ const n=Math.min(Number(c.equityBatchSize),state.universe.equities.length), batch=[]; for(let i=0;i<n;i++)batch.push(state.universe.equities[(state.equityCursor+i)%state.universe.equities.length]); state.equityCursor=(state.equityCursor+n)%state.universe.equities.length; const snaps=await getStockSnapshots('live',batch.map(a=>a.symbol),{feed:c.stockFeed}); for(const a of batch){ const m=mom(snaps[a.symbol]); if(!m||m.price<Number(c.minEquityPrice))continue; const dv=m.price*m.volume, eligible=dv>=Number(c.minDailyDollarVolume)&&!blocked.has(a.symbol)&&canTradeMarket(trades,a.symbol); snapOut[a.symbol]={assetClass:'us_equity',momentumPct:Number(m.momentumPct.toFixed(4)),thresholdPct:c.entryMomentumPct,eligible,dollarVolume:Math.round(dv)}; if(eligible&&m.momentumPct>=c.entryMomentumPct)candidates.push({symbol:a.symbol,name:a.name||a.symbol,assetClass:'us_equity',dollarVolume:dv,...m}); }}
  candidates.sort((a,b)=>b.momentumPct-a.momentumPct); state.signalSnapshot=Object.fromEntries(Object.entries(snapOut).slice(-25)); state.topCandidates=candidates.slice(0,10).map(x=>({symbol:x.symbol,assetClass:x.assetClass,momentumPct:Number(x.momentumPct.toFixed(4)),price:Number(x.price.toFixed(6))})); return candidates[0]||null;
}
async function closeTrade(trade,price,reason){ const qty=Number(trade.filled_qty||trade.qty); if(!Number.isFinite(qty)||qty<=0)throw new Error('Open trade has no filled quantity to close.'); const crypto=trade.asset_class==='crypto'||String(trade.market).includes('/'); const order=await placeOrder({mode:'live',symbol:trade.market,qty,side:'sell',type:'market',timeInForce:crypto?'gtc':'day'}); const fill=await waitForFill('live',order.id); if(fill.status!=='filled')throw new Error(`Exit order ${order.id} was not filled (status: ${fill.status}).`); const exit=Number(fill.filled_avg_price||price), entry=Number(trade.entry_price), pnl=(exit-entry)*Number(fill.filled_qty||qty), result=pnl>=0?'win':'loss'; const all=store.getAll('trades'),i=all.findIndex(t=>t.id===trade.id); if(i>=0){all[i]={...all[i],exit_price:exit,pnl:Number(pnl.toFixed(4)),result,exit_reason:reason,exit_order_id:order.id,closed_at:new Date().toISOString()};store.saveAll('trades',all);} const session=store.getOne('sessions',trade.session_id); if(session){session.consecutive_losses=result==='loss'?Number(session.consecutive_losses||0)+1:0;recomputeSessionStats(session,all);store.update('sessions',session.id,session);} state.openTradeId=null; }
async function manage(){ if(!state.openTradeId)return false; state.lastDecision='managing open position'; const t=store.getOne('trades',state.openTradeId); if(!t||t.result!==null){state.openTradeId=null;return false;} const ac=t.asset_class||(String(t.market).includes('/')?'crypto':'us_equity'), p=await getLatestTradablePrice('live',t.market,ac), entry=Number(t.entry_price), move=((p-entry)/entry)*100, age=(Date.now()-new Date(t.timestamp||t.created_at).getTime())/60000,c=cfg(); if(move>=c.takeProfitPct)await closeTrade(t,p,`take profit +${move.toFixed(3)}%`); else if(move<=-c.stopLossPct)await closeTrade(t,p,`stop loss ${move.toFixed(3)}%`); else if(age>=c.maxHoldMinutes)await closeTrade(t,p,`max hold ${age.toFixed(1)}m`); return true; }
async function enter(){ const session=store.getOne('sessions',state.sessionId); if(!session)throw new Error('Live bot session was not found.'); const halt=checkHaltConditions(session); if(halt.halt){store.update('sessions',session.id,{status:'halted',halt_reason:halt.reason,completed_at:new Date().toISOString()});stop(`Safety halt: ${halt.reason}`);return;} const best=await scan(); if(!best){state.lastDecision=`scanning ${state.universe.equities.length+state.universe.crypto.length} Alpaca tradable assets — waiting for momentum signal`;return;} state.lastDecision=`entry signal ${best.symbol} +${best.momentumPct.toFixed(4)}%`; const a=await getAccount('live'), bp=Number(a.buying_power||a.cash||0), equity=Number(a.equity||a.portfolio_value||a.cash||0), riskFraction=Number(tradingCfg().riskPerTrade ?? 0.02), desiredNotional=equity*riskFraction, notional=Math.min(desiredNotional,bp); if(!Number.isFinite(riskFraction)||riskFraction<=0||riskFraction>1)throw new Error('Risk per trade must be between 0 and 1 (0.02 = 2%).'); if(!Number.isFinite(notional)||notional<1)throw new Error('Insufficient live buying power for the configured risk-based trade size.'); state.lastDecision=`entry signal ${best.symbol} +${best.momentumPct.toFixed(4)}% · sizing $${notional.toFixed(2)} (${(riskFraction*100).toFixed(2)}% of equity)`; const order=await placeOrder({mode:'live',symbol:best.symbol,notional:Number(notional.toFixed(2)),side:'buy',type:'market',timeInForce:best.assetClass==='crypto'?'gtc':'day'}), fill=await waitForFill('live',order.id); if(fill.status!=='filled')throw new Error(`Entry order ${order.id} was not filled (status: ${fill.status}).`); const ep=Number(fill.filled_avg_price||best.price), t=createTrade({sessionId:session.id,market:best.symbol,marketName:best.name,direction:'LONG',conviction:'standard',entryPrice:ep}); Object.assign(t,{asset_class:best.assetClass,alpaca_order_id:order.id,qty:Number(fill.filled_qty),filled_qty:Number(fill.filled_qty),entry_signal:{momentum_pct:Number(best.momentumPct.toFixed(4)),source:'alpaca minute snapshot'}}); store.insert('trades',t); state.openTradeId=t.id; state.lastDecision=`entered ${best.symbol} at ${ep}`; }
async function tick(){ if(!state.running)return; try{ const g=gate(); if(!g.allowed){stop(`Live Gate closed while bot was running: ${g.reason}`);return;} if(store.getConfig('tradingMode',{mode:'paper'}).mode!=='live'){stop('Trading mode changed away from live.');return;} state.lastTickAt=new Date().toISOString(); state.lastError=null; const had=await manage(); if(!had&&!state.openTradeId)await enter(); }catch(e){console.error('[live-bot]',e);state.lastError=e.message;state.lastDecision=`stopped on error: ${e.message}`;stop(e.message);}finally{schedule();} }
router.get('/status',(req,res)=>res.json(pub()));
router.post('/start',async(req,res)=>{try{if(state.running)return res.status(409).json({error:'Live bot is already running.',...pub()});const g=gate();if(!g.allowed)return res.status(403).json({error:`Live bot blocked: ${g.reason}`});if(store.getConfig('tradingMode',{mode:'paper'}).mode!=='live')return res.status(403).json({error:'Switch Trading Mode to live before starting the live bot.'});const a=await getAccount('live');if(a.trading_blocked)return res.status(403).json({error:'Alpaca reports trading_blocked=true for this account.'});const open=store.getAll('trades').find(t=>t.result===null);if(open)return res.status(409).json({error:`Refusing to start while local trade ${open.id} is still marked open.`});const eq=Number(a.equity||a.cash||0);if(!Number.isFinite(eq)||eq<=0)return res.status(403).json({error:'Live account has no available equity.'});await refreshUniverse(true);const session=createSession({mode:'live',startingCapital:eq});store.insert('sessions',session);Object.assign(state,{running:true,sessionId:session.id,startedAt:new Date().toISOString(),lastTickAt:null,lastError:null,openTradeId:null,lastDecision:`starting — loaded ${state.universe.equities.length+state.universe.crypto.length} Alpaca tradable assets`,signalSnapshot:{},topCandidates:[]});setImmediate(tick);res.json(pub());}catch(e){res.status(500).json({error:e.message});}});
router.post('/stop',async(req,res)=>{stop();state.lastDecision='stopped by user';try{if(state.openTradeId){const t=store.getOne('trades',state.openTradeId);if(t&&t.result===null){const ac=t.asset_class||(String(t.market).includes('/')?'crypto':'us_equity'),p=await getLatestTradablePrice('live',t.market,ac);await closeTrade(t,p,'live bot stopped by user');}}if(state.sessionId){const s=store.getOne('sessions',state.sessionId);if(s&&s.status==='running')store.update('sessions',s.id,{status:'halted',halt_reason:'Live bot stopped by user',completed_at:new Date().toISOString()});}res.json(pub());}catch(e){state.lastError=`Bot stopped, but open-position close failed: ${e.message}`;res.status(500).json({error:state.lastError,...pub()});}});
export default router;
