// V36 EQUITY PAPER/SHADOW FORWARD VALIDATOR — NO BROKER ORDER PATH.
// Purpose: tomorrow's equity forward test after V35 failed expectation testing.

import { getStockSnapshots, getStockBars, getMarketNews, getTradableAssets } from './alpacaClient.js';
import { buildEquityMarketRegime } from './strategyEngine.js';
import { evaluateEquityCandidateV36 } from './equityStrategyV36.js';
import { buildNewsIntelligenceMapV34 } from './marketIntelligenceV34.js';

const CORE_SYMBOLS=(process.env.V36_EQUITY_CORE_SYMBOLS||'SPY,QQQ,IWM,DIA,AAPL,MSFT,NVDA,AMZN,META,GOOGL,TSLA,AMD,AVGO,PLTR,COIN,MSTR,SOFI,INTC,MU,SMCI,RIVN,NIO,LCID,MARA,RIOT,HOOD,UBER,CRM,ORCL,NFLX,F,SNAP,BAC,CCL,AAL').split(',').map(s=>s.trim().toUpperCase()).filter(Boolean);
const POLL_MS=Math.max(30000,Number(process.env.V36_EQUITY_SHADOW_POLL_MS||60000));
const STARTING_EQUITY=Math.max(1000,Number(process.env.V36_EQUITY_SHADOW_EQUITY||100000));
const RISK_FRACTION=Math.min(0.01,Math.max(0.001,Number(process.env.V36_EQUITY_SHADOW_RISK||0.0075)));
const MAX_POSITIONS=Math.max(1,Math.min(12,Number(process.env.V36_EQUITY_SHADOW_MAX_POSITIONS||6)));
const MIN_SCORE=Math.max(0,Math.min(10,Number(process.env.V36_EQUITY_SHADOW_MIN_SCORE||6.2)));
const ROTATING_BATCH_SIZE=Math.max(100,Math.min(1200,Number(process.env.V36_EQUITY_ROTATING_BATCH_SIZE||500)));
const DETAIL_LIMIT=Math.max(20,Math.min(150,Number(process.env.V36_EQUITY_DETAIL_LIMIT||100)));
const FIRST_SIGNAL_MINUTE_ET=Math.max(570,Number(process.env.V36_FIRST_SIGNAL_MINUTE_ET||(9*60+35)));
const MAX_GROSS_EXPOSURE=Math.min(1.25,Math.max(0.25,Number(process.env.V36_MAX_GROSS_EXPOSURE||1.0)));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const n=(v,f=NaN)=>Number.isFinite(Number(v))?Number(v):f;
const compact=s=>String(s||'').replace('/','').toUpperCase();
const ET=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',weekday:'short',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});
function etNow(d=new Date()){const p=Object.fromEntries(ET.formatToParts(d).map(x=>[x.type,x.value]));return{weekday:p.weekday,minutes:Number(p.hour)*60+Number(p.minute),dateKey:`${p.year}-${p.month}-${p.day}`};}
function sessionState(d=new Date()){const {weekday,minutes}=etNow(d);if(!['Mon','Tue','Wed','Thu','Fri'].includes(weekday))return'closed';if(minutes<570)return'pre';if(minutes<960)return'regular';return'closed';}
function barMinuteTs(bar){const raw=bar?.t??bar?.timestamp??bar?.time;const ms=raw?Date.parse(raw):NaN;return Number.isFinite(ms)?Math.floor(ms/60000)*60000:NaN;}

let paperEquity=STARTING_EQUITY,peakEquity=STARTING_EQUITY,maxDrawdownPct=0,scanCount=0,qualificationCount=0,entryCount=0,consecutiveLosses=0;
let newsMap={},newsFetchedAt=0,assetMap=new Map(),universe=[],assetsFetchedAt=0,equityCursor=0,lastFinalDate=null,activeSessionDate=null;
const positions=new Map(),closed=[],lastPrices=new Map();
function updateDD(){peakEquity=Math.max(peakEquity,paperEquity);maxDrawdownPct=Math.max(maxDrawdownPct,((peakEquity-paperEquity)/peakEquity)*100);}
function grossExposure(){return [...positions.values()].reduce((a,p)=>a+p.notional,0);}
function summary(){const wins=closed.filter(x=>x.pnl>0).length,losses=closed.filter(x=>x.pnl<0).length,grossWin=closed.filter(x=>x.pnl>0).reduce((a,x)=>a+x.pnl,0),grossLoss=Math.abs(closed.filter(x=>x.pnl<0).reduce((a,x)=>a+x.pnl,0));return{strategy:'V36',startingEquity:STARTING_EQUITY,paperEquity:Number(paperEquity.toFixed(2)),returnPct:Number(((paperEquity/STARTING_EQUITY-1)*100).toFixed(3)),maxDrawdownPct:Number(maxDrawdownPct.toFixed(3)),scans:scanCount,qualifications:qualificationCount,entries:entryCount,openPositions:positions.size,closedTrades:closed.length,wins,losses,winRatePct:closed.length?Number((wins/closed.length*100).toFixed(2)):0,profitFactor:grossLoss>0?Number((grossWin/grossLoss).toFixed(3)):grossWin>0?999:0,netPnl:Number((paperEquity-STARTING_EQUITY).toFixed(2)),grossExposure:Number(grossExposure().toFixed(2)),grossExposurePct:Number((grossExposure()/paperEquity*100).toFixed(1)),consecutiveLosses};}
function resetSession(dateKey){if(!activeSessionDate)activeSessionDate=dateKey;if(activeSessionDate===dateKey)return;activeSessionDate=dateKey;equityCursor=0;consecutiveLosses=0;console.log('[V36 equity shadow] NEW_SESSION',dateKey);}
async function refreshAssets(){if(Date.now()-assetsFetchedAt<30*60000&&universe.length)return;const assets=await getTradableAssets('live');const rows=Array.isArray(assets?.equities)?assets.equities:[];assetMap=new Map(rows.map(a=>[String(a.symbol||'').toUpperCase(),a]));universe=[...assetMap.keys()];assetsFetchedAt=Date.now();if(equityCursor>=universe.length)equityCursor=0;console.log('[V36 equity shadow] UNIVERSE',JSON.stringify({equities:universe.length}));}
async function refreshNews(now,symbols){if(Date.now()-newsFetchedAt<5*60000)return;try{const r=await getMarketNews('live',{symbols,start:new Date(now-24*3600000),end:now,limit:50,includeContent:false});const a=Array.isArray(r?.news)?r.news:Array.isArray(r?.articles)?r.articles:[];newsMap=buildNewsIntelligenceMapV34({articles:a,now});}catch(e){console.warn('[V36 equity shadow] news unavailable:',e.message);}finally{newsFetchedAt=Date.now();}}
function rotatingSymbols(){if(!universe.length)return[...new Set(CORE_SYMBOLS)];const count=Math.min(ROTATING_BATCH_SIZE,universe.length),batch=[];for(let i=0;i<count;i++)batch.push(universe[(equityCursor+i)%universe.length]);equityCursor=(equityCursor+count)%universe.length;return[...new Set([...CORE_SYMBOLS,...positions.keys(),...batch,'SPY','QQQ'])];}
function snapshotScore(s){const trade=n(s?.latestTrade?.p??s?.minuteBar?.c);if(!(trade>0))return-Infinity;const mo=n(s?.minuteBar?.o,trade),mm=mo>0?Math.abs((trade/mo-1)*100):0,prev=n(s?.prevDailyBar?.c),dm=prev>0?Math.abs((trade/prev-1)*100):0,vol=Math.max(0,n(s?.dailyBar?.v,0)),dv=trade*vol,bid=n(s?.latestQuote?.bp),ask=n(s?.latestQuote?.ap),spread=bid>0&&ask>0?(ask-bid)/((ask+bid)/2)*100:0.25;return mm*4+dm*.35+Math.log10(dv+10)*.15-spread*2;}
function closePosition(symbol,exit,reason,now){const p=positions.get(symbol);if(!p||!(exit>0))return false;const grossPct=p.direction==='LONG'?((exit/p.entry)-1)*100:((p.entry/exit)-1)*100,netPct=grossPct-p.costPct,pnl=p.notional*netPct/100;paperEquity+=pnl;updateDD();const t={symbol,direction:p.direction,entry:p.entry,exit,netPct:Number(netPct.toFixed(4)),pnl:Number(pnl.toFixed(2)),score:p.score,reason,openedAt:new Date(p.openedAt).toISOString(),closedAt:now.toISOString()};closed.push(t);positions.delete(symbol);consecutiveLosses=pnl<0?consecutiveLosses+1:pnl>0?0:consecutiveLosses;console.log('[V36 equity shadow] EXIT',JSON.stringify(t));return true;}
function checkExit(symbol,snapshot,now){const p=positions.get(symbol);if(!p)return false;const bar=snapshot?.minuteBar||{},latest=n(snapshot?.latestTrade?.p??bar?.c);if(!(latest>0))return false;lastPrices.set(symbol,latest);const bm=barMinuteTs(bar),em=Math.floor(p.openedAt/60000)*60000,barIsAfterEntry=Number.isFinite(bm)&&bm>em;const high=barIsAfterEntry?n(bar?.h,latest):latest,low=barIsAfterEntry?n(bar?.l,latest):latest;let exit=null,reason=null;if(p.direction==='LONG'){const sh=low<=p.stopPrice,th=high>=p.targetPrice;if(sh){exit=p.stopPrice;reason=th?'STOP_SAME_BAR':'STOP';}else if(th){exit=p.targetPrice;reason='TARGET';}}else{const sh=high>=p.stopPrice,th=low<=p.targetPrice;if(sh){exit=p.stopPrice;reason=th?'STOP_SAME_BAR':'STOP';}else if(th){exit=p.targetPrice;reason='TARGET';}}if(!exit&&now.getTime()-p.openedAt>=p.maxHoldMinutes*60000){exit=latest;reason='MAX_HOLD';}return exit?closePosition(symbol,exit,reason,now):false;}
function enter(signal,now){if(!signal||positions.has(signal.symbol)||positions.size>=MAX_POSITIONS)return false;const plan=signal.signal?.exitPlan||{},stopPct=n(plan.stopLossPct),targetPct=n(plan.takeProfitPct),entry=n(signal.price);if(!(stopPct>0)||!(targetPct>0)||!(entry>0))return false;const riskDollars=paperEquity*RISK_FRACTION,rawNotional=Math.min(paperEquity*.20,riskDollars/(stopPct/100)),capacity=Math.max(0,paperEquity*MAX_GROSS_EXPOSURE-grossExposure()),notional=Math.min(rawNotional,capacity);if(!(notional>=500))return false;const direction=signal.direction,stopPrice=direction==='LONG'?entry*(1-stopPct/100):entry*(1+stopPct/100),targetPrice=direction==='LONG'?entry*(1+targetPct/100):entry*(1-targetPct/100);const p={symbol:signal.symbol,direction,score:signal.score,entry,stopPrice,targetPrice,notional,costPct:n(plan.estimatedRoundTripCostPct,.04),maxHoldMinutes:Math.max(5,n(plan.maxHoldMinutes,45)),openedAt:now.getTime()};positions.set(signal.symbol,p);entryCount++;console.log('[V36 equity shadow] ENTER',JSON.stringify({...p,openedAt:now.toISOString(),notional:Number(notional.toFixed(2))}));return true;}
async function finalize(now){if(positions.size){try{const snaps=await getStockSnapshots('live',[...positions.keys()],{feed:'iex'});for(const s of [...positions.keys()]){const latest=n(snaps?.[s]?.latestTrade?.p??snaps?.[s]?.minuteBar?.c,lastPrices.get(s));if(latest>0)closePosition(s,latest,'SESSION_CLOSE',now);}}catch{for(const s of [...positions.keys()]){const latest=n(lastPrices.get(s));if(latest>0)closePosition(s,latest,'SESSION_CLOSE_LAST_PRICE',now);}}}console.log('[V36 equity shadow] FINAL_DAILY',JSON.stringify({at:now.toISOString(),summary:summary(),closed:closed.slice(-200)}));}
async function scanOnce(){const now=new Date(),et=etNow(now);resetSession(et.dateKey);const session=sessionState(now);if(session==='closed'){if(lastFinalDate!==et.dateKey){await finalize(now);lastFinalDate=et.dateKey;}return;}if(session!=='regular'||et.minutes<FIRST_SIGNAL_MINUTE_ET)return;await refreshAssets();const symbols=rotatingSymbols();await refreshNews(now,symbols);const snaps=await getStockSnapshots('live',symbols,{feed:'iex'});scanCount++;const exited=new Set();for(const s of [...positions.keys()])if(snaps?.[s]&&checkExit(s,snaps[s],now))exited.add(s);const ranked=symbols.filter(s=>!positions.has(s)&&!exited.has(s)&&snaps?.[s]).map(s=>({symbol:s,score:snapshotScore(snaps[s])})).filter(x=>Number.isFinite(x.score)).sort((a,b)=>b.score-a.score);const detail=[...new Set([...ranked.slice(0,DETAIL_LIMIT).map(x=>x.symbol),'SPY','QQQ'])];const bars=await getStockBars('live',detail,{timeframe:'1Min',start:new Date(now-12*3600000),end:now,limit:10000,feed:'iex',maxPages:4});const marketRegime=buildEquityMarketRegime(bars.SPY||[],bars.QQQ||[]),candidates=[],rejectCounts=new Map();for(const symbol of ranked.slice(0,DETAIL_LIMIT).map(x=>x.symbol)){const rows=bars[symbol]||[],snapshot=snaps[symbol];if(!snapshot||rows.length<12){rejectCounts.set('insufficient detailed market data',(rejectCounts.get('insufficient detailed market data')||0)+1);continue;}const result=evaluateEquityCandidateV36({asset:assetMap.get(symbol)||{symbol,shortable:false,easy_to_borrow:false},snapshot,bars:rows,marketRegime,intelligence:newsMap[compact(symbol)]||null,now,mode:'paper-shadow',config:{equityV36ScoreThreshold:MIN_SCORE}});if(result.signal){qualificationCount++;candidates.push(result.signal);}else{const reason=result?.reason||result?.diagnostics?.reason||'V36: rejected';rejectCounts.set(reason,(rejectCounts.get(reason)||0)+1);}}candidates.sort((a,b)=>Number(b.score)-Number(a.score));for(const sig of candidates){if(positions.size>=MAX_POSITIONS)break;enter(sig,now);}const topRejects=[...rejectCounts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([reason,count])=>({reason,count}));console.log('[V36 equity shadow] SCAN',JSON.stringify({at:now.toISOString(),marketRegime,batchScanned:symbols.length,detailed:Math.min(DETAIL_LIMIT,ranked.length),qualified:candidates.length,top:candidates.slice(0,8).map(x=>({symbol:x.symbol,direction:x.direction,score:x.score,playbook:x.signal?.playbook})),topRejects,summary:summary()}));}
console.log('[V36 equity shadow] starting',JSON.stringify({startingEquity:STARTING_EQUITY,riskFraction:RISK_FRACTION,maxPositions:MAX_POSITIONS,maxGrossExposure:MAX_GROSS_EXPOSURE,minScore:MIN_SCORE,detailLimit:DETAIL_LIMIT,pollMs:POLL_MS,orderPlacement:false,liveTrading:false}));
while(true){try{await scanOnce();}catch(e){console.error('[V36 equity shadow] scan error',e?.stack||e?.message||e);}await sleep(POLL_MS);}
